### PR TITLE
Fixes #67 (Gif duplication)

### LINKED ISSUE #67: Gifs duplication issue when long pressing
When long pressing on multiple gifs (one after another) the newly selected gif is copied to the position of previous as seen here:

preview

Running on Android 7.1

### PR DESCRIPTION
**Pull request by charlesdurham**
It's not a bullet proof solution but it does significantly cut down on the occurrences (to almost none).

### CODE REVIEW

**Comment by charlesdurham** [comment]
https://github.com/hzsweers/CatchUp/issues/67

**Comment by hzsweers** [comment]
It looks like it's fixed in Glide master now. Would it be better to just wait for the next release?

**Comment by charlesdurham** [comment]
I think the NonAutostarting targets or some simpler variant where the DribblerTarget doesn't call super onResourceReady might still be worthwhile to avoid immediately starting and stopping the gif.

**Comment by charlesdurham** [comment]
Immediately starting and stopping each gif adds the overhead of decoding and holding in memory a second bitmap.

**Comment by hzsweers** [comment]
Fair point. Looks like 4.3 was released, do you want to include that update in this PR?

**Comment by charlesdurham** [comment]
Done, I saw https://github.com/bumptech/glide/issues/2541 but wasn't able to reproduce.

**Comment by hzsweers** [comment]
Awesome! Installing now, going to run for a day or so tomorrow to see if anything comes up

**Comment by hzsweers** [comment]
So functionally everything seems fine, but one thing I wanted to check. I've noticed I get leak canary reports now originating from Glide. It does seem to be rooted in a custom implementation I wrote, but wanted to see if this looks related to your change:

image

**Comment by charlesdurham** [comment]
It looks like a change in Glide's `RequsetManger` between 4.2. and 4.3. In 4.3 `RequestManger` holds onto any context reference in it's constructor `this.context = context`.

I haven't quiet tracked down why/how the `RequestManger` is being kept around but either way I don't see any reason for that context reference not to be `context.getBaseContext()`.

**Comment by hzsweers** [comment]
Interesting. Want to make both of those changes in this PR?

**Comment by charlesdurham** [comment]
I did some more investigation and glide ties a `RequestManager`'s start/stop/destroy to an internal fragment. You can see most of this in [RequestManagerRetriever](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestManagerRetriever.java) and [RequestManagerFragment](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestManagerFragment.java).

The simplest solution is to let glide do it's thing and not try to tie the request manager lifecycle to a controller. I think that's also the best solution here since it doesn't seem like much is gained by tying the request manager's lifecycle to a controller.

That said; I also created a `Glide.with()` that ties a request manager to a controller's lifecycle (because why not): https://gist.github.com/charlesdurham/7ab78fb97038ec7d6fc7a3d2ebec23fb

I didn't add that gist to my PR but let me know if you want to go that route instead.

**Comment by hzsweers** [comment]
Yep I'd agree with just removing it and letting Glide handling it. Can revisit your gist in the future if we decide there needs to be a reason to tie to the controller lifecycle. Want to just delete the requestmanager impl as part of this PR?

**Comment by charlesdurham** [comment]
Not sure what you mean by request manager impl, I didn't add that gist to the PR, was really just me messing around.

**Comment by hzsweers** [comment]
As in remove my existing custom implementation too and just use vanilla glide

**Comment by charlesdurham** [comment]
Ah sorry, took me a bit to wrap my head around what's going on.

**Comment by charlesdurham** [comment]
I think all those sub-classes get generated from `@GlideModule`. I was hoping there would be some way to hook into glide's initialization and set the default request options without all of those classes being generated but I can't find one.

There's also a generated `GlideApp` which is already being used in the app and supports adding generated methods (right now it just mimics Glide's static APIs).  Seems slightly better to use `GlideApp.with()` instead of `Glide.with()` so I made that minor change in my PR. 

I feel like there's still a chance I totally missed what you were after so if that's the case sorry again.

**Comment by hzsweers** [comment]
Ah I was specifically talking about removing this function while you're at it since I think it's unused now - https://github.com/hzsweers/CatchUp/blob/8861c3bfb96db6b0a6c80480803ece4caabce50e/app/src/main/kotlin/io/sweers/catchup/GlideConfiguration.kt#L60-L60

It looks like you've done that though, so I think this is good to go!

**Comment by hzsweers** [comment]
Thanks again for this and bearing with me on code review cycles (been traveling a lot with 2 conferences in the last week, and one more this weekend x_x)

**Comment by hzsweers** [comment]
I bet @nickbutcher would be interested in this fix in Plaid too if you're feeling contribute-y :)

**Pull request merged**
