### PR TITLE
Convert list_item_general to use ConstraintLayout

### PR DESCRIPTION
**Pull request by R4md4c**
I've read your complaints about ConstraintLayout and I've been converting lately lots of our legacy layouts to ConstraintLayout, so I thought in giving you a hand.

I tried it in emulator and it looks like this, hope it looks fine.

screenshot_1508789195

### CODE REVIEW

**Comment by hzsweers** [comment]
Thanks for this! I'll try to take a look tonight

**Comment by hzsweers** [comment]
So it looks like this mostly works, but has issues when the metadata container at the top is gone

image

**Comment by R4md4c** [comment]
Sorry about that! I introduced a 16dp guideline to the left of the views, and introduced a gone margin 16dp that will be applied to the title in case the tags container is hidden.

**Comment by hzsweers** [comment]
Awesome! I'm traveling right now so it might not be till Sunday/Monday that I can look at this again, but just wanted to drop a comment that I did see it :)

**Comment by hzsweers** [comment]
That definitely fixed the empty header issue! I've installed and played around with it a bit, but noticed a few more issues:
- Separator dots are different colors for some reason

- When tag is hidden, both dots are still visible

image

- When Score is hidden, separator dot is still visible

image

- Dots seem to have more margin on the left than the right

image

- I'm not sure what the issue is, but constraints seem to get messed up on the changelog example (which uses the same layout too)

image

**Comment by R4md4c** [comment]
Thanks for your time in reporting these issues! I wasn't be able to see these issues because Hacker News for instance didn't work for me since it needs to initialize Firebase,  maybe you know how to fix that, do I need to go through creating a Firebase account for that?
Also I'm not be able to view the changelog since I get 401 HTTP Error, what do I need to do to make it work?
Here is the stacktrace
```
Could not load changelog.
                                                                                com.apollographql.apollo.exception.ApolloHttpException: HTTP 401 Unauthorized
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:105)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:28)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:93)
                                                                                    at com.google.firebase.perf.network.zzg.onResponse(Unknown Source:16)
                                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                    at java.lang.Thread.run(Thread.java:764)
```

**Comment by R4md4c** [comment]
Also the weird thing is that Slashdot is displayed fine for me, while it has an extra dot in your screenshot.

screenshot_1509219203

**Comment by hzsweers** [comment]
Ah yeah, both of those require API keys :/. You could stub it to return some dummy data in the meantime, I've been thinking about adding that for debugging in general

**Comment by R4md4c** [comment]
@hzsweers I've managed to stub the Hacker News, and Changelog items, and I think they look fine now. Can you please look at them? Hopefully they are fixed.

**Comment by hzsweers** [comment]
Almost there! One more :)

(Top is with constraintlayout, bottom is current master)

* Needs the same goneMargin trick for if the attribution section is empty I think (see the gap on the second item)

image

Interestingly, I've noticed that that the colored divider bullet is themed on master too, so that's not an issue in your PR. Sorry for the false alarm!

**Comment by hzsweers** [comment]
Eesh, apparently I have terrible memory and did the colored divider over a month ago, before the release even. I think what's throwing me off is the divider when there's only one themed text with the timestamp. I'll fix that on master

**Comment by R4md4c** [comment]
Unfortunately I had to add few lines of code  to be able to change the vertical centreing of the views when source or author visibilities are changed. Hopefully everything looks fine now.

**Comment by hzsweers** [comment]
Pretty good, I did notice a slight regression though. When the tag container is empty, it has extra ~8dp height still that gives it asymmetrically more height than the bottom

image

**Comment by R4md4c** [comment]
The title had margin top 4dp when it is constrained to the bottom of the timestamp, and this 4dp still exists when the timestamp gets hidden, thus the asymmetrical shape that you were saying. I've added a goneMarginTop 0dp that will be apply when the timestamp is hidden. Hope this fix the issue.

**Comment by hzsweers** [comment]
I still see the extra space at the top in this case too :/. 

Wouldn't `app:layout_goneMarginTop="4dp"` on the title only apply if the title was gone (whereas this case the title is visible but the tags group is gone?)

**Comment by R4md4c** [comment]
Well `app:layout_goneMarginTop="4dp"` should be `0dp` not `4dp`! no idea why did I commit it with `4dp`, probably it was mistakenly committed while reverting some stuff to the stub code that I've put to display the items.

And to answer your question, `layout_goneMargin*` are margins that are applied to the target view when the connected view has visibility as GONE (In that case the target view is `title` and the connected view is `timestamp`)

**Comment by hzsweers** [comment]
Still no dice :/

image

**Comment by R4md4c** [comment]
I think there is a bug in ConstraintLayout that makes it doesn't respect under certain conditions the goneMarginTop that I put to the title when the timestamp is hidden (check the image, there is top margin even though it shouldn't).

I've posted a bug at the Android AOSP tracker for that see[1].

screenshot_1509572231

Meanwhile unfortunately, I'll set the margin top to zero through code, until this issue is fixed.

[1] https://issuetracker.google.com/issues/68768935

**Comment by R4md4c** [comment]
I've added the code that sets the top margin to 0. 
Here is how it looks now.

image

**Comment by hzsweers** [comment]
I think this is the one! Great work, I really appreciate all the work and bearing with me on reviews :)

**Comment by R4md4c** [comment]
No problems! Sorry for the hassle that I caused you and the time that you've taken in reviewing my work.

In future we might need to separate the general_list_item.xml into smaller layouts, since it is overkill that in views like the license we just use 2 from the available 9 TextViews that are in the layout.

**Pull request merged**
