### PR TITLE
Default values support in moshkt

### PR DESCRIPTION
**Pull request by hzsweers**
This implements an idea that Ryan and I were talking about, where we create a defaults-only instance first before then copying it with the potentially new values if they're present.

Example code in `Foo`:

```kotlin
@MoshiSerializable
data class Foo(
    @Json(name = "first_name") val firstName: String,
    @Json(name = "last_name") val lastName: String,
    val age: Int,
    val nationalities: List<String> = emptyList(),
    val weight: Float,
    val tattoos: Boolean = false,
    val race: String?,
    val hasChildren: Boolean = false,
    val favoriteFood: String? = null,
    val favoriteDrink: String? = "Water"
)
```

Output:
```kotlin
class Foo_JsonAdapter(private val moshi: Moshi) : JsonAdapter<Foo>() {
  override fun fromJson(reader: JsonReader): Foo? {
    if (reader.peek() == JsonReader.Token.NULL) {
      reader.nextNull<Any>()
    }
    lateinit var firstName: String
    lateinit var lastName: String
    var age = 0
    var nationalities: List<String>? = null
    var weight = 0.0f
    var tattoos: Boolean? = null
    var race: String? = null
    var hasChildren: Boolean? = null
    var favoriteFood: String? = null
    var favoriteDrink: String? = null
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.nextName()) {
        "first_name" -> firstName = moshi.adapter(String::class.java).fromJson(reader)!!
        "last_name" -> lastName = moshi.adapter(String::class.java).fromJson(reader)!!
        "age" -> age = moshi.adapter(Int::class.java).fromJson(reader)!!
        "nationalities" -> nationalities = moshi.adapter<List<String>>(Types.newParameterizedType(List::class.java, String::class.java)).fromJson(reader)!!
        "weight" -> weight = moshi.adapter(Float::class.java).fromJson(reader)!!
        "tattoos" -> tattoos = moshi.adapter(Boolean::class.java).fromJson(reader)!!
        "race" -> race = moshi.adapter(String::class.java).fromJson(reader)
        "hasChildren" -> hasChildren = moshi.adapter(Boolean::class.java).fromJson(reader)!!
        "favoriteFood" -> favoriteFood = moshi.adapter(String::class.java).fromJson(reader)
        "favoriteDrink" -> favoriteDrink = moshi.adapter(String::class.java).fromJson(reader)
        else -> reader.skipValue()
      }
    }
    reader.endObject()
    return Foo(firstName = firstName,
        lastName = lastName,
        age = age,
        weight = weight,
        race = race).let {
          it.copy(nationalities = nationalities ?: it.nationalities,
              tattoos = tattoos ?: it.tattoos,
              hasChildren = hasChildren ?: it.hasChildren,
              favoriteFood = favoriteFood ?: it.favoriteFood,
              favoriteDrink = favoriteDrink ?: it.favoriteDrink)
        }
  }

  override fun toJson(writer: JsonWriter, value: Foo?) {
    if (value == null) {
      writer.nullValue()
      return
    }
    writer.beginObject()
    writer.name("first_name")
    moshi.adapter(String::class.java).toJson(writer, value.firstName)
    writer.name("last_name")
    moshi.adapter(String::class.java).toJson(writer, value.lastName)
    writer.name("age")
    moshi.adapter(Int::class.java).toJson(writer, value.age)
    writer.name("nationalities")
    moshi.adapter<List<String>>(Types.newParameterizedType(List::class.java, String::class.java)).toJson(writer, value.nationalities)
    writer.name("weight")
    moshi.adapter(Float::class.java).toJson(writer, value.weight)
    writer.name("tattoos")
    moshi.adapter(Boolean::class.java).toJson(writer, value.tattoos)
    if (value.race != null) {
      writer.name("race")
      moshi.adapter(String::class.java).toJson(writer, value.race)
    }
    writer.name("hasChildren")
    moshi.adapter(Boolean::class.java).toJson(writer, value.hasChildren)
    if (value.favoriteFood != null) {
      writer.name("favoriteFood")
      moshi.adapter(String::class.java).toJson(writer, value.favoriteFood)
    }
    if (value.favoriteDrink != null) {
      writer.name("favoriteDrink")
      moshi.adapter(String::class.java).toJson(writer, value.favoriteDrink)
    }
    writer.endObject()
  }
}
```

### CODE REVIEW

**Comment by hzsweers** [comment]
Note that I'd like to do proper integration tests in the disabled `integration` module, but I seem to be stuck on a bizarre gradle/kotlin issue where it can't find any plugins I add on new projects. Going to follow that up separately.

```
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pandanomic/dev/android/personal/CatchUp/tooling/moshkt/integration/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':tooling:moshkt:integration'.
> Could not find implementation class 'org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper' for plugin 'org.jetbrains.kotlin.jvm' specified in jar:file:/Users/pandanomic/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-gradle-plugin/1.2.21/e53ec8cdacbc461d750d0add731e803e5d4cf71c/kotlin-gradle-plugin-1.2.21.jar!/META-INF/gradle-plugins/org.jetbrains.kotlin.jvm.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 3s
Cause: org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper
```

**Comment by swankjesse** [comment]
This looks fabulous. One request: looking up adapters on demand is expensive;  please prefetch em!

**Comment by rharter** [comment]
Great! Came out even cleaner than we talked about. (how did we forget about Elvis?!?) I'm really loving how there's close to no change to your Kotlin data classes to achieve this. 

Agree about prefetching adapters, also means you need fewer requests (only one string adapter is needed, etc).

**Comment by hzsweers** [comment]
Yep prefetching is next on my list :)

**Pull request merged**
